name: Slack Incoming Webhooks
on:
  release:
    types: [edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out theis repo
      - uses: actions/checkout@v2

      - name: echo release note
        run: |
          echo "- github.event.release --------------------------"
          echo ${{ github.event.release }}
          echo "- github.event.release.html_url --------------------------"
          echo "${{ github.event.release.html_url }}"
          echo "- github.event.release.name --------------------------"
          echo "${{ github.event.release.name }}"
          echo "- github.event.release.tag_name --------------------------"
          echo "${{ github.event.release.tag_name }}"
          echo "- github.event.release.body --------------------------"
          echo '${{ github.event.release.body }}'
          echo "---------------------------"
          release_body='${{ github.event.release.body }}'
          release_body=${release_body//$'\r\n'/\\n}
          release_body=${release_body//$'\n'/\\n}
          echo "${release_body}"
          echo "---------------------------"
          echo "---------------------------"

