name: Slack Incoming Webhooks
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # release note の内容をそのまま使用できないので改行コードを置換
    - id: get_release_note
      name: echo release note
      run: |
        # 改行コードをエスケープする
        release_body="${{ github.event.release.body }}"
        release_body=${release_body//$'\r\n'/\\n}
        release_body=${release_body//$'\n'/\\n}
        echo "::set-output name=body::$release_body"

    # Start a Slack workflow using a webhook trigger
    # https://github.com/slackapi/slack-github-action
    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: |
          {
            "text": "本日以下の内容がリリースされました:tada:\n\n```${{ steps.get_release_note.outputs.body }}```\n\n対応ありがとうございました:clap:\n詳細はこちら: ${{ github.event.release.html_url }}",
            "unfurl_links": false
          }
      env:
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
